### ISSUE TITLE
提出期限がない課題に表示上のバグが発生する

### ISSUE THREAD

**Issue by Shion1305** [OhVIton/Assignment-Manager-for-YNU-LMS#4]
いきなりIssue投稿してしまいすみません。
Routeで少し話したことのある、市川詩恩です!
少し気になった点があったので投稿させて頂きました!
直してみてmerge requestを出してみましたので
変更点をご確認いただいた上で承認して頂きましたら
幸いです!
拡張機能製作応援してます!

提出期限が設定されていない課題が登録された時に`1970/1/1 9:00:00`と表示されてしまう
`show_homework_storage.js`で`assignment['due']=null`となってしまっているため

<img width="303" alt="Issue_ChromeExtension" src="https://user-images.githubusercontent.com/20254962/163392813-45d07808-d296-4fd3-941e-eb58a321d0f8.png">

**Comment by Shion1305** [comment]
#5 にてこの問題を修正した。

**Comment by OhVIton** [comment]
マージしました！
