### ISSUE TITLE
dueがなかった時にも日付の計算がされてしまう

### ISSUE THREAD

**Issue by Shion1305** [OhVIton/Assignment-Manager-for-YNU-LMS#6]
due=nullの時にも、提出期限までの時間を計算するコードが実行されてしまう。

**Comment by OhVIton** [comment]
マージしました！

**Comment by shion1305** [comment]
#8 でこのIssueを直したのですがマージされていないようです...m(__)m

**Comment by Shion1305** [comment]
> マージしました！

#8  でこのIssueを直したのですがマージされていないようです...m(__)m

**Comment by OhVIton** [comment]
マージできたはず！
