### ISSUE TITLE
[Error] Uncaught (in promise) TypeError: Cannot read properties of null (reading '2')

### ISSUE THREAD

**Issue by Shion1305** [OhVIton/Assignment-Manager-for-YNU-LMS#7]
原因は未解明ですが次のエラーログが出ました。
<img width="533" alt="image" src="https://user-images.githubusercontent.com/20254962/163429064-d4b1e07a-5ca5-4cff-af96-0e4ebfb31a85.png">

**Comment by OhVIton** [comment]
LMS英語で使ってたらなりますね
講義名の形式が
日本語: 講義名(日)[講義名(英)][講義ID]
英語: 講義名(英)[講義ID]
と、日本語と英語で違うからですね
以前のLMSだと英語でも日本語の講義名併記していたので、FJTの改悪といえます

**Comment by OhVIton** [comment]
とりあえず要素数足りないやつはAAA1234というダミーの講義IDを返すことで対応しました
