### ISSUE TITLE
"Clear overdue assigmnents"が機能しない

### ISSUE THREAD

**Issue by nogamiryohma** [OhVIton/Assignment-Manager-for-YNU-LMS#9]
以下の様な画面で `clear overdue assignments` を押しても期限切れの課題が削除されなかった。
![image](https://github.com/OhVIton/Assignment-Manager-for-YNU-LMS/assets/93119262/5eea2f34-db56-4d4a-8410-fe267a95b153)

**Comment by OhVIton** [comment]
報告ありがとうございます！

今修正版のver2.4.1をChrome Web Storeに送信したので、じきアップデートが来ると思います！

**Comment by nogamiryohma** [comment]
@OhVIton ありがとうございます！いつも大変お世話になってます！これからも使い続けます！
